variable "location" { # Self explanatory - these come from tfvars as its the directory tf apply runs
  description = "Location of resource deployed"
  type        = string
}

variable "location_short_name" { # Self explanatory - these come from tfvars as its the directory tf apply runs 
  description = "Location of resource deployed in short name"
  type        = string
}

variable "default_tags" {
  description = "Common default tags generated by the pipeline run."
  type        = map(string)
  default     = {}
}

variable "project" {
  description = "The name of the project for the resource."
  type        = string
}

variable "subscription_id" {
  description = "Subscription ID generated by the pipeline run."
  type        = string
}

variable "tenant_id" {
  type        = string
  description = "Tenant ID generated by the pipeline run."
}

variable "environment" {
  description = "Environment generated by the pipeline run."
  type        = string
}

variable "environment_short_name" { # Self explanatory - these come from tfvars as its the directory tf apply runs
  description = "Environment short nam.e of the deploying environment"
  type        = string
}

variable "branch_hash" {
  description = "Environment branch hash for dev-test"
  type        = string
  default     = "null"
}
