variable "subscription_id" {
  description = "Subscription ID generated by the pipeline run."
  type        = string
}

variable "tenant_id" {
  type        = string
  description = "Tenant ID generated by the pipeline run."
}

variable "environment" {
  type        = string
  description = "Environment generated by the pipeline run."
}

variable "environment_short_name" {
  type        = string
  description = "Environment generated by the pipeline run."
}

