variable "project" {
  description = "The name of the project for the resource."
  type        = string
}

variable "tenant_id" {
  type        = string
  description = "Tenant ID generated by the pipeline run."
}

variable "subscription_id" {
  description = "Subscription ID generated by the pipeline run."
  type        = string
}

variable "branch_hash" {
  description = "Environment branch hash for dev-test"
  type        = string
  default     = "null"
}

variable "location" {
  description = "Location of resource deployed"
  type        = string
}

variable "environment_short_name" {
  description = "Environment short name of the deploying environment"
  type        = string
}

variable "location_short_name" {
  description = "Location of resource deployed in short name"
  type        = string
}
